# Generated by Django 3.1.6 on 2021-02-20 22:21

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuestionData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField()),
                ("data", models.JSONField()),
            ],
            options={
                "db_table": "questions_data",
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "survey",
            },
        ),
        migrations.CreateModel(
            name="SurveyData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.survey"
                    ),
                ),
            ],
            options={
                "db_table": "survey_data",
            },
        ),
        migrations.CreateModel(
            name="SurveyDataType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField(unique=True)),
                (
                    "fields",
                    models.JSONField(validators=[api.models.validate_survey_data_type]),
                ),
            ],
            options={
                "db_table": "survey_data_type",
            },
        ),
        migrations.CreateModel(
            name="SurveyLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_datetime", models.DateTimeField()),
                ("action", models.CharField(max_length=1)),
                ("username", models.TextField()),
                ("data", models.JSONField()),
                (
                    "parent",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.survey",
                    ),
                ),
            ],
            options={
                "db_table": "survey_log",
            },
        ),
        migrations.CreateModel(
            name="SurveyDataLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_datetime", models.DateTimeField()),
                ("action", models.CharField(max_length=1)),
                ("username", models.TextField()),
                ("data", models.JSONField()),
                (
                    "parent",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.surveydata",
                    ),
                ),
            ],
            options={
                "db_table": "survey_data_log",
            },
        ),
        migrations.AddField(
            model_name="surveydata",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.surveydatatype"
            ),
        ),
    ]
