# Generated by Django 3.1.6 on 2021-02-13 19:57

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


trigger_sql = '''
CREATE OR REPLACE FUNCTION public.{table_name}_log_trigger()
 RETURNS trigger LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP = 'DELETE' THEN
    INSERT INTO {table_name}_log(parent_id, event_datetime, action, username, data) VALUES (OLD.id, now(), 'D', session_user, to_json(OLD));
  ELSE
    INSERT INTO {table_name}_log(parent_id, event_datetime, action, username, data) VALUES (NEW.id, now(), TG_OP::char , session_user, to_json(NEW));
  END IF;
  RETURN NULL;
END;
$function$;

CREATE TRIGGER log_{table_name} AFTER INSERT OR UPDATE OR DELETE ON {table_name} FOR EACH ROW EXECUTE FUNCTION {table_name}_log_trigger();
'''


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey',
            },
        ),
        migrations.CreateModel(
            name='SurveyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.survey')),
            ],
            options={
                'db_table': 'survey_data',
            },
        ),
        migrations.CreateModel(
            name='SurveyDataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(unique=True)),
                ('fields', models.JSONField(validators=[api.models.validate_list])),
            ],
            options={
                'db_table': 'survey_data_type',
            },
        ),
        migrations.CreateModel(
            name='SurveyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_datetime', models.DateTimeField()),
                ('action', models.CharField(max_length=1)),
                ('username', models.TextField()),
                ('data', models.JSONField()),
                ('parent', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='api.survey')),
            ],
            options={
                'db_table': 'survey_log',
            },
        ),
        migrations.CreateModel(
            name='SurveyDataLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_datetime', models.DateTimeField()),
                ('action', models.CharField(max_length=1)),
                ('username', models.TextField()),
                ('data', models.JSONField()),
                ('parent', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='api.surveydata')),
            ],
            options={
                'db_table': 'survey_data_log',
            },
        ),
        migrations.AddField(
            model_name='surveydata',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.surveydatatype'),
        ),
        migrations.RunSQL(trigger_sql.format(table_name='survey')),
        migrations.RunSQL(trigger_sql.format(table_name='survey_data')),
    ]
